#!/usr/bin/env sh 
. "$(dirname "$0")/_/husky.sh"

# Find all .sln files in the repository
solution_files=$(find . -name "*.sln")

# Run dotnet format for each solution
for solution in $solution_files
do
  echo "Running dotnet format on $solution"
  dotnet format --verify-no-changes "$solution"
done
